# Generated by Django 5.0.4 on 2026-07-20 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("short_description", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of key project feature bullet points",
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        default=list,
                        help_text="List of technology names e.g. ['React', 'Django', 'PostgreSQL']",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fullstack", "Full Stack"),
                            ("frontend", "Frontend"),
                            ("backend", "Backend API"),
                            ("mobile", "Mobile Application"),
                            ("devops", "DevOps / Infrastructure"),
                            ("ai_ml", "AI / Machine Learning"),
                        ],
                        default="fullstack",
                        max_length=50,
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="completed",
                        max_length=50,
                    ),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_demo_url", models.URLField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
    ]
