# Generated by Django 5.0.4 on 2026-07-20 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend Development"),
                            ("backend", "Backend Development"),
                            ("database", "Databases & ORM"),
                            ("cloud", "Cloud Infrastructure"),
                            ("devops", "DevOps & CI/CD"),
                            ("programming_languages", "Programming Languages"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(
                        default=85, help_text="Percentage between 0 and 100"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        help_text="React Icon string or SVG icon key", max_length=50
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "display_order", "name"],
                "abstract": False,
            },
        ),
    ]
